### ISSUE TITLE
Tooltips are indented in indented paragraphs

### ISSUE THREAD

**Issue by SierraKomodo** [SierraKomodo/worldanvil-templates#2]
![firefox_2018-08-15_01-20-50](https://user-images.githubusercontent.com/11140088/44138709-a4557cbc-a029-11e8-8479-5777feefe719.png)

Relevant bbcode:

```bbcode
[in]
    [p]Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque in viverra eros, non malesuada ligula. Sed est est, vulputate sed leo dictum, mollis pretium orci. In pharetra laoreet [tooltip:tooltip]justo[/tooltip], vel cursus enim convallis quis. Integer nunc enim, scelerisque et lobortis vel, lacinia at sem. Nullam eu arcu placerat, accumsan massa vel, malesuada metus. Vestibulum enim est, [tooltip:tooltip]consequat in ex eget[/tooltip], maximus ornare mi. Pellentesque rutrum porta purus nec consequat. Nullam porttitor, augue nec rhoncus pellentesque, est justo bibendum est, a auctor massa tellus ac odio. Proin volutpat lorem quam. [/p]
[/in]
```

**Comment by SierraKomodo** [comment]
As it turns out, this was actually a bug in WorldAnvil's core CSS, not in GalaxyAnvil.

**Comment by SierraKomodo** [comment]
Recommended temporary fix in custom CSS:

```css
.user-css .paragraph-indent, .user-css-extended .paragraph-indent {
    text-indent: inherit;
}

.user-css .paragraph-indent p, .user-css-extended .paragraph-indent p {
    text-indent: 50px;
}

.user-css .paragraph-indent :not(p), .user-css-extended .paragraph-indent :not(p) {
    text-indent: 0;
}
```
